### PR TITLE
Fix/contract stamp defaults

### PR DESCRIPTION
**Pull request by nduchak**

### CODE REVIEW

**Comment by nikita-fuchs** [comment]
Is the `deposit` key still being used ?

**Comment by nduchak** [comment]
Yes, we are using it in contract-create transaction.

**Comment by nikita-fuchs** [comment]
Then we should also set this to 0 by default. It was the value that was deposited as the contract's initial balance, right?

**Comment by nduchak** [comment]
Yes, you are right  👌

**Pull request merged**
