### PR TITLE
Fix compatibility with cra4

### PR DESCRIPTION
**Pull request by davidyuk**
rises issue https://github.com/aeternity/aepp-sdk-js/issues/1529
Firstly I merged these changes in #1528, but after I found out that it breaks wallet extension example

### CODE REVIEW

**Comment by marc0olo** [comment]
@davidyuk I was just told by @subhod-i that updating the react boilerplate is still blocked by this. is this correct or false assumption?

**Comment by davidyuk** [comment]
in PM with Subhod we agreed to update boilerplate to react-script@5 which uses webpack 5 that is compatible with sdk

**Comment by davidyuk** [comment]
https://github.com/aeternity/remove-me--babel-plugin-transform-default-named-imports
@marc0olo do you have permissions to remove this repo?
the fix I tried to implement here is not working, azure team planning to fix it on their side

**Comment by marc0olo** [comment]
> @marc0olo do you have permissions to remove this repo?

I am almighty 😛 deleted ;)

**Pull request closed without merging**
