### PR TITLE
Add initial readthedocs configuration, fix some docs

### PR DESCRIPTION
**Pull request by davidyuk**
based on #1077 

As I see, ReadTheDocs is significantly better than GH pages because they provide docs for different versions. The complication was the need to build API docs there using the newer version of npm (by default they provide npm@3).

https://aepp-sdk-js.readthedocs.io/en/latest/

### CODE REVIEW

**Review by mradkov — APPROVED** [review]
Looks good to me.

**Comment by mradkov** [comment]
@davidyuk can you rebase with develop? Thanks

**Review by nikita-fuchs — APPROVED** [review]

**Comment by mradkov** [comment]
@nikita-fuchs I asked @davidyuk to rebase so we don't have such commits in the git tree: https://github.com/aeternity/aepp-sdk-js/pull/1084/commits/b533a6842aa5187abc3ebf5eb9bbac8a984b951f

**Comment by nikita-fuchs** [comment]
My bad.

Milen Radkov <notifications@github.com> schrieb am Mi., 4. Nov. 2020, 15:49:

**Pull request merged**
