### PR TITLE
docs: inline examples in guides

### LINKED ISSUE #1538: Reference examples code in documentation instead of copy-pasting between them
I've tested https://docs.github.com/en/github-ae@latest/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet in a usual md file and it works! For example in https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/guides/build-wallet.md we have the same code as in https://github.com/aeternity/aepp-sdk-js/blob/develop/examples/browser/wallet-web-extension/src/background.js and we can just reference it there instead of manual copy/pasting. The problem is that it may be not supported by our documentation hub: https://aeternity.com/aepp-sdk-js/v11.0.1/

### PR DESCRIPTION
**Pull request by davidyuk**
closes #1538

### CODE REVIEW

**Comment by janmichek** [comment]
@davidyuk 

Are those links working for you?
I see a blank screen

https://github.com/aeternity/aepp-sdk-js/blob/32fbb8b44b08025d7abe53bdfa275893271cbf56/examples/browser/aepp/src/StoreAeSdkPlugin.js#L34-L49

https://github.com/aeternity/aepp-sdk-js/blob/32fbb8b44b08025d7abe53bdfa275893271cbf56/examples/browser/wallet-web-extension/src/content-script.js#L1-L27

**Comment by janmichek** [comment]
(when I directly put it to address bar)

**Comment by davidyuk** [comment]
I have the same behaviour (Chrome reports 406 error), maybe it is some ddos protection? Anyway, latest version looks good at github:
https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/guides/connect-aepp-to-wallet.md
https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/guides/build-wallet.md
the same as in mkdocs:
https://aeternity.com/aepp-sdk-js/develop/guides/connect-aepp-to-wallet/
https://aeternity.com/aepp-sdk-js/develop/guides/build-wallet/

**Comment by janmichek** [comment]
> I have the same behaviour (Chrome reports 406 error), maybe it is some ddos protection? Anyway, latest version looks good at github: https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/guides/connect-aepp-to-wallet.md https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/guides/build-wallet.md the same as in mkdocs: https://aeternity.com/aepp-sdk-js/develop/guides/connect-aepp-to-wallet/ https://aeternity.com/aepp-sdk-js/develop/guides/build-wallet/

Nice, these links seems better!

However I am not a big fan of this change.
In my opinion these tutorials should be as most simplistic as possible.
Now it relies on Vuex and some of its configuration.
Before was just simple copy pasting of snippets and it worked out of the box.

**Comment by janmichek** [comment]
obrazek

**Pull request merged**
