### PR TITLE
chore(example): Update sdk in example app

### PR DESCRIPTION
**Pull request by nduchak**

### CODE REVIEW

**Comment by etharner** [comment]
I'm receiving this error when using example aepp and identity both updated to this branch
image

**Comment by nduchak** [comment]
> I'm receiving this error when using example aepp and identity both updated to this branch
> image

You need to fund this account before deploying contract

**Comment by davidyuk** [comment]
@nduchak but before it was not necessary, why you decided to change it?

**Comment by nduchak** [comment]
> @nduchak but before it was not necessary, why you decided to change it?

What not necessary???Have tokens on account to make transaction?

**Comment by davidyuk** [comment]
> > @nduchak but before it was not necessary, why you decided to change it?
> 
> What not necessary???Have tokens on account to make transaction?

I'm about this change: https://github.com/aeternity/aepp-sdk-js/commit/ccfbd6b3f53671a5b40a8e9a63e2d4cd75661a45#diff-19756c1304d22bf30c05d2b6624cc5faL52-R52

**Pull request merged**
