### PR TITLE
fix typo in examples - networkId

### PR DESCRIPTION
**Pull request by mradkov**

### CODE REVIEW

**Comment by nduchak** [comment]
@mradkov Hey, i will add this fix to release branch

**Comment by nduchak** [comment]
Included here: https://github.com/aeternity/aepp-sdk-js/pull/323

**Comment by mradkov** [comment]
Cool, the [documentation](https://dev.aepps.com/aepp-sdk-js/docs/usage.html) is still not updated yet tho.

**Comment by ricricucit** [comment]
That can probably be fixed by @Pegahbit, right?

**Comment by mradkov** [comment]
> That can probably be fixed by @Pegahbit, right?

I've just created an issue in the documentation hub, after discussing this with @Pegahbit. So it will be fixed soon I think.

**Pull request closed without merging**
