### PR TITLE
[WIP] Implement GA awareness of State Channels

### PR DESCRIPTION
**Pull request by mpowaga**
- [x] Implement https://github.com/aeternity/aeternity/pull/2502.
- [x] Make changes backwards compatible with aeternity@3.0.1
- [ ] Ensure that GA is correctly handled

### CODE REVIEW

**Comment by nduchak** [comment]
Looks like i brake branch on Jenkins. Can you tell me if this changes compatible with node 3.3.0?

**Comment by mpowaga** [comment]
This PR is compatible with 3.2.0 and 3.3.0. One test case is failing with 3.1.0 for unknown reason. Tested on my local machine. Somehow test won't start on jenkins.

**Comment by nduchak** [comment]
Can you close this PR and create another one from new branch. This may fix Jenkins;)

**Comment by mpowaga** [comment]
Closing in favour of #544 which fixes jenkins.

**Pull request closed without merging**
