### PR TITLE
Simplify bigNumberToByteArray function

### PR DESCRIPTION
**Pull request by davidyuk**

### CODE REVIEW

**Comment by nduchak** [comment]
@denis Some time ago you already do the same, but for some reason it's not work as expected. I was tested it using python-sdk and we have the different result.

**Comment by davidyuk** [comment]
@nduchak Can you show a case in with my proposal works differently? probably this case should be added as a unit test

**Comment by noandrea** [comment]
if ain't broken dont fixit

**Comment by davidyuk** [comment]
You shouldn't invent the wheel, my proposal makes code easier to read and maintain.

**Pull request merged**
