### PR TITLE
docs(aens): remove usages of removed `createAensDelegationSignature`

### LINKED ISSUE #1461: Drop `createAensDelegationSignature`, `createOracleDelegationSignature`
https://github.com/aeternity/aepp-sdk-js/pull/1439#pullrequestreview-921407481

### PR DESCRIPTION
**Pull request by davidyuk**
Was missed in 24699f15896be0984fc8396979148fa97288dab4
closes #1461

### CODE REVIEW

**Comment by marc0olo** [comment]
🤔 can't this still be used? it is implemented in https://github.com/aeternity/aepp-sophia-examples/blob/master/test/aensDelegation.js#L65

will there be a breaking change in the new SDK version? does that mean a contract instance is needed to create the delegation signature?

**Comment by davidyuk** [comment]
> will there be a breaking change in the new SDK version?

Yep, it would be sdk@13

> does that mean a contract instance is needed to create the delegation signature?

Yes, from my perspective these signature delegation is highly connected to contract functionality

**Comment by marc0olo** [comment]
> Yes, from my perspective these signature delegation is highly connected to contract functionality

disagree here. I only need the contract address to create the delegation signature. it's independent of the logic of any contract. so now every user who wants to provide a delegation signature needs to somehow create a contract instance just to be able to provide that signature. is that correct?

if that's the case I would ask you to rollback this change please

**Comment by marc0olo** [comment]
maybe we can support both ways, not sure. but to me it's not linked to the actual contract logic

**Comment by davidyuk** [comment]
I don't have a strong opinion here, so the creation of a delegation signature would be a method of AeSdk again.

**Comment by marc0olo** [comment]
> I don't have a strong opinion here, so the creation of a delegation signature would be a method of AeSdk again.

thanks @davidyuk ! :)

**Pull request merged**
